version: '3'
services:
  webhawk:
    build: .
    container_name: webhawk
    volumes:
      - .:/app  # Synchroniser le dossier actuel avec /app dans le conteneur
    stdin_open: true
    tty: true
